---
# handlers file for imperva
- name: Register Agent
  command: >-
    {{ imperva_installation_dir }}/ragent/bin/cli
    --dcfg {{ imperva_installation_dir }}/ragent/etc
    --dvar {{ imperva_installation_dir }}/ragent/var
    --dtarget {{ imperva_installation_dir }}/ragent/etc
    --dlog {{ imperva_installation_dir }}/ragent/etc/logs/cli
    registration advanced-register
    registration-type=Primary
    is-db-agent=true
    ragent-name={{ inventory_hostname }}
    gw-ip={{ gateway_ip }}
    gw-port={{ app_imperva_port }}
    manual-settings-activation=Automatic
    monitor-network-channels=Both
    password={{ gateway_pass }}

- name: Register Installer
  command: >-
    {{ imperva_installation_dir }}/installer/bin/cliinstaller
    --dcfg {{ imperva_installation_dir }}/installer/etc
    --dvar {{ imperva_installation_dir }}/installer/var
    --dtarget {{ imperva_installation_dir }}/installer/etc
    --dlog {{ imperva_installation_dir }}/installer/etc/logs/cli
    registration advanced-register
    registration-type=Primary
    is-db-agent=true
    ragent-name={{ inventory_hostname }}
    gw-ip={{ gateway_ip }}
    gw-port={{ app_imperva_port }}
    manual-settings-activation=Automatic
    monitor-network-channels=Both
    password={{ gateway_pass }}
    package-folder-size={{ app_imperva_fldr }}

- name: Start Agent service
  command: >-
    {{ imperva_installation_dir }}/ragent/bin/rainit start

- name: Start Install Manager
  command: >-
    {{ imperva_installation_dir }}/installer/bin//rainstallerinit start

- name: Restart Agent service
  command: >-
    {{ imperva_installation_dir }}/ragent/bin/rainit restart

- name: Restart Install Manager
  command: >-
    {{ imperva_installation_dir }}/installer/bin//rainstallerinit restart

- name: Get Agent status
  command: >-
    echo q | sudo {{ imperva_installation_dir }}/ragent/bin/racli 2> /dev/null | egrep "Release|Status"
